### ISSUE TITLE
Crash al intentar traer la imagen de la tarjeta

### ISSUE THREAD

**Issue by mejiagarcia** [paymentez/paymentez-android#7]
Hola Team, espero se encuentren bien.

Utilizando este SDK, al intentar poner una tarjeta número por número, (sin copiar y pegar), la app me hace crash con este error que viene de la librería:

Mis pruebas: 
1. Una tarjeta VISA
2. La tarjeta de prueba que ponen en su documentación, la que empieza por 41111....

![Screen Shot 2020-02-05 at 7 57 01 PM](https://user-images.githubusercontent.com/14830877/73896762-f056e980-4851-11ea-9a69-c94d0bf09fd2.png)

```
2020-02-05 19:56:00.958 7892-7892/com.master.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.master.android, PID: 7892
    java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in /data/app/com.master.android-1/base.apk)
        at com.paymentez.android.view.CardMultilineWidget.updateDrawable(CardMultilineWidget.java:941)
        at com.paymentez.android.view.CardMultilineWidget.updateBrand(CardMultilineWidget.java:857)
        at com.paymentez.android.view.CardMultilineWidget.access$700(CardMultilineWidget.java:57)
        at com.paymentez.android.view.CardMultilineWidget$3.onCardBrandChanged(CardMultilineWidget.java:555)
        at com.paymentez.android.view.CardNumberEditText.updateCardBrand(CardNumberEditText.java:256)
        at com.paymentez.android.view.CardNumberEditText.access$100(CardNumberEditText.java:34)
        at com.paymentez.android.view.CardNumberEditText$2.onResponse(CardNumberEditText.java:283)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run(DefaultCallAdapterFactory.java:83)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

¿Hay alguna forma de tokenizar una tarjeta del lado del cliente sin usar este SDK? , este error nos está perjudicando de manera muy grave.

Gracias y saludos!

**Comment by dogcalas** [comment]
I have the same issue! Please Fix

**Comment by ergo-notch** [comment]
Can you test again the sdk with implementation 'com.github.paymentez:paymentez-android:v1.3.5'
